pipeline{
    agent none
    stages{
        stage('Build'){
            steps{
                echo 'This is Build Stage'
            }
        }
        stage ('Test'){
            steps{
                echo 'This is test stage'
            }
        }
        stage('Prod'){
            steps{
                echo 'This is prod stage'
            }
        }
    }
}